name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit black codespell flake8 isort mypy pytest pyupgrade safety
      - run: bandit --recursive --skip B101,B311 .
      - run: black --check . || true
      - run: codespell --skip="./README.pt-BR.md"
      - run: flake8 . --count --max-complexity=12 --max-line-length=100 --show-source --statistics
      - run: isort --check-only . || true  # --profile black
      - run: pip install -r requirements.txt
      - run: mypy --install-types --non-interactive .
      - run: pytest .
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
